PRN231_Web_Razor/Pages/Admin/AccountManagement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Project_Cinema_PRN231.domain.room;
using Project_Cinema_PRN231.model;

namespace Library.Pages.Admin
{
    public class AccountManagementModel : PageModel
    {


        //public AccountManagementModel(IUnitOfWork unitOfWork)
        //{
        //    _unitOfWork = unitOfWork;
        //}
        [BindProperty]
        public SysUser User { get; set; }
        public IList<SysUser> Users { get; set; }

          public void OnGet()
          {
            HttpClient _httpClient = new HttpClient();
            HttpResponseMessage response = _httpClient.GetAsync("http://localhost:5000/api/SysUser/getAll").Result;
            var SysUsers = response.Content.ReadFromJsonAsync<List<SysUser>>().Result;
            ViewData["SysUser"] = SysUsers.ToList();

        }

        //public IActionResult OnPostEditUser()
        //{
        //    int userId = int.Parse(Request.Form["id"]);
        //    string role = Request.Form["role"];
        //    string status = Request.Form["status"];
        //    User u = _unitOfWork.UserRepository.Find(userId);
        //    u.UserRole = role;
        //    u.Status = bool.Parse(status);
        //    _unitOfWork.UserRepository.Update(u);
        //    _unitOfWork.SaveChange();
        //    return RedirectToPage();
        //}
        //public IActionResult OnPostAddUser()
        //{
        //    _unitOfWork.UserRepository.Add(User);
        //    _unitOfWork.SaveChange();
        //    return RedirectToPage();
        //}
    }
}

PRN231_Web_Razor/Pages/Admin/CategoryManagement.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Project_Cinema_PRN231.domain.category;
using Project_Cinema_PRN231.model;

namespace Library.Pages.Admin
{
    public class CategoryManagementModel : PageModel
    {

        public string mess { get; set; }
        public IList<Category> Categories { get; set; }
        [BindProperty]
        public Category Category { get; set; }

        [Required]
        public IFormFile Image { get; set; }
        public void OnGet()
        {
            HttpClient _httpClient = new HttpClient();
            HttpResponseMessage response = _httpClient.GetAsync("http://localhost:5000/api/Category/GetCategory").Result;
            var list = response.Content.ReadFromJsonAsync<List<Category>>().Result;
            Categories = (IList<Category>)list.ToList();
        }

        public async Task<IActionResult> OnPostEditCategory()
        {
            var idUpdate = int.Parse(Request.Form["id"]);
            var nameUpdate = Request.Form["name"];

            HttpClient client = new HttpClient();
            HttpResponseMessage responseById = client.GetAsync("http://localhost:5000/api/Category/GetCategory/?$filter=id%20eq%20" + idUpdate).Result;
            var category = responseById.Content.ReadFromJsonAsync<List<Category>>().Result;
            Category c = category[0];
            c.Name = nameUpdate;
            var file = Request.Form.Files["newimage"];

            if (file != null && file.Length > 0)
            {
                var fileName = file.FileName;
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "assets", "images", "category", fileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                c.Image = "/assets/images/category/" + fileName;
            }

            //call api update
            var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5000/api/Category/Update");
            request.Headers.Add("Accept", "*/*");
            var jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(c);
            var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
            request.Content = content;
            // Await the asynchronous call to send the request
            var response = await client.SendAsync(request);

            return RedirectToPage();
        }

        public IActionResult OnPostAddCategory()
        {
            var fileName = Image.FileName;
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "category", fileName);
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                Image.CopyTo(stream);
            }
            Category.Image = "/img/category/" + fileName;

            //_unitOfWork.CategoryRepository.Add(Category);
            //_unitOfWork.SaveChange();

            return RedirectToPage();
        }

        //public IActionResult OnGetDeleteCategory(int categoryId)
        //{
        //    try
        //    {
        //        _unitOfWork.CategoryRepository.Delete(categoryId);
        //        _unitOfWork.SaveChange();
        //        return new JsonResult("1");

        //    }
        //    catch (Exception e)
        //    {
        //        return new JsonResult("0");

        //    }

        //}
        public IActionResult OnGetExportFile()
        {
            HttpClient _httpClient = new HttpClient();
            HttpResponseMessage response = _httpClient.GetAsync("http://localhost:5000/api/Category/GetCategory").Result;
            var list = response.Content.ReadFromJsonAsync<List<Category>>().Result;
            var data = (IList<Category>)list.ToList();

            MemoryStream memoryStream = new MemoryStream();
            StreamWriter streamWriter = new StreamWriter(memoryStream);

            streamWriter.WriteLine("CategoryId," + "CategoryName");
            // Ghi dữ liệu vào tập tin
            foreach (var item in data)
            {
                streamWriter.WriteLine(item.Id + "," + item.Name);
            }
            streamWriter.Flush();
            memoryStream.Seek(0, SeekOrigin.Begin);

            // Trả về tập tin đã tạo
            return File(memoryStream, "text/csv", "categories.csv");
        }
        //public string ImportMessage { get; set; }

        //public async Task<IActionResult> OnPostImportFile(IFormFile csvFile)
        //{
        //    if (csvFile == null || csvFile.Length == 0)
        //    {
        //        ImportMessage = "No file selected.";
        //        return RedirectToPage();
        //    }

        //    using (var reader = new StreamReader(csvFile.OpenReadStream(), Encoding.UTF8))
        //    {
        //        // Đọc dữ liệu từ tập tin CSV
        //        var csvData = await reader.ReadToEndAsync();
        //        List<Category> chiatay = new List<Category>();
        //        List<Category> all = _unitOfWork.CategoryRepository.GetAll().ToList();
        //        var lines = csvData.Split("\n");
        //        for (int i = 1; i < lines.Length; i++)
        //        {
        //            Category c;
        //            var line = lines[i].Trim();
        //            if (line == "")
        //            {
        //                break;
        //            }
        //            var value = line.Split(',');
        //            if (all.FirstOrDefault(x => x.CategoryId == int.Parse(value[0])) == null)
        //            {
        //                c = new Category
        //                {
        //                    CategoryName = value[1],
        //                    Image = ""
        //                };
        //                _unitOfWork.CategoryRepository.Add(c);
        //                _unitOfWork.SaveChange();
        //            }
        //        }

        //        ImportMessage = "File imported successfully.";
        //    }

        //    return RedirectToPage();
        //}
    }
}

PRN231_Web_Razor/Pages/Admin/FilmCalenderManagement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Project_Cinema_PRN231.domain.filmcalender;
using Project_Cinema_PRN231.domain.libraryfilm;
using Project_Cinema_PRN231.domain.room;
using Project_Cinema_PRN231.model;
using System.Text;

namespace PRN231_Web_Razor.Pages.Admin
{
    public class FilmCalenderManagementModel : PageModel
    {
        public void OnGet()
        {
            HttpClient _httpClient = new HttpClient();

            HttpResponseMessage response = _httpClient.GetAsync("http://localhost:5000/api/Room/getAll").Result;
            var RoomDtos = response.Content.ReadFromJsonAsync<List<RoomDto>>().Result;
            ViewData["RoomDto"] = RoomDtos.ToList();

            response = _httpClient.GetAsync("http://localhost:5000/api/FilmCalender/GetAll").Result;
            var filmCalenders = response.Content.ReadFromJsonAsync<List<FilmCalenderDto>>().Result;

            ViewData["FilmCalenderDto"] = filmCalenders.ToList();
        }

        public async Task<IActionResult> OnPostEditFilm()
        {
            var idFilm = Request.Form["id"];
            HttpClient client = new HttpClient();
            HttpResponseMessage response = client.GetAsync("http://localhost:5000/api/FilmCalender/GetAll?$filter=id%20eq%20" + idFilm).Result;
            var list1 = response.Content.ReadFromJsonAsync<List<FilmCalender>>().Result;
            FilmCalender lb = list1[0];

            lb.RoomId = int.Parse(Request.Form["roomId"]);
            lb.Date = DateTime.Parse(Request.Form["date"]);
            lb.StartTime = TimeSpan.Parse(Request.Form["startTime"]);
            lb.EndTime = TimeSpan.Parse(Request.Form["endTime"]);
            lb.Price = decimal.Parse(Request.Form["price"]);
            lb.UpdatedAt = DateTime.Now;

            //call api update
            var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5000/api/FilmCalender/Update");
            request.Headers.Add("Accept", "*/*");
            var jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(lb);
            var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
            request.Content = content;
            // Await the asynchronous call to send the request
            var response1 = await client.SendAsync(request);

            return RedirectToPage();

        }
        public async Task<IActionResult> OnPostImportFile(IFormFile csvFile)
        {
            if (csvFile == null || csvFile.Length == 0)
            {
                return RedirectToPage();
            }

            using (var reader = new StreamReader(csvFile.OpenReadStream(), Encoding.UTF8))
            {
                //
                var csvData = await reader.ReadToEndAsync();


                //List<> all = _unitOfWork.CategoryRepository.GetAll().ToList();
                HttpClient _httpClient = new HttpClient();
                HttpResponseMessage response = _httpClient.GetAsync("http://localhost:5000/api/FilmCalender/getAll").Result;
                var all = response.Content.ReadFromJsonAsync<List<FilmCalender>>().Result;

                var lines = csvData.Split("\n");
                for (int i = 1; i < lines.Length; i++)
                {
                    FilmCalender c;
                    var line = lines[i].Trim();
                    if (line == "")
                    {
                        break;
                    }
                    var value = line.Split(',');

                    int roomId = int.Parse(value[3]);
                    int filmId = int.Parse(value[4]);
                    DateTime newDate = DateTime.Parse(value[0]);
                    TimeSpan newStartTime = TimeSpan.Parse(value[1]);
                    TimeSpan newEndTime = TimeSpan.Parse(value[2]);

                    var overlappingFilms = all.Where(x => x.RoomId == roomId &&
                                                          x.Date == newDate &&
                                                          ((newStartTime >= x.StartTime && newStartTime < x.EndTime) ||
                                                           (newEndTime > x.StartTime && newEndTime <= x.EndTime) ||
                                                           (newStartTime <= x.StartTime && newEndTime >= x.EndTime)));

                    if (!overlappingFilms.Any())
                    {
                        FilmCalender c1 = new FilmCalender
                        {
                            Date = newDate,
                            StartTime = newStartTime,
                            EndTime = newEndTime,
                            RoomId = roomId,
                            FilmId = filmId,
                            Price = decimal.Parse(value[5]),
                            IsDeleted = false,
                            CreatedAt = DateTime.Now,
                        };

                        //call api add

                        var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5000/api/FilmCalender/Add");
                        request.Headers.Add("Accept", "*/*");
                        var jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(c1);
                        var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                        request.Content = content;
                        // Await the asynchronous call to send the request
                        var response1 = await _httpClient.SendAsync(request);
                    }
                }
            }

            return RedirectToPage();
        }

        public IActionResult OnGetExportFile()
        {
            HttpClient client = new HttpClient();
            var response = client.GetAsync("http://localhost:5000/api/FilmCalender/GetAll").Result;
            var list1 = response.Content.ReadFromJsonAsync<List<FilmCalenderDto>>().Result;
            var data = (IList<FilmCalenderDto>)list1.ToList();
            MemoryStream memoryStream = new MemoryStream();
            StreamWriter streamWriter = new StreamWriter(memoryStream);
            streamWriter.WriteLine("id," + "FilmName," + "RoomName," + "Date," + "StartTime," + "EndTime," + "Price");
            foreach (var item in data)
            {
                streamWriter.WriteLine(item.Id + "," + item.FilmName + "," + item.RoomName + "," + item.Date +
                    "," + item.StartTime + "," + item.EndTime + "," + item.Price );
            }
            streamWriter.Flush();
            memoryStream.Seek(0, SeekOrigin.Begin);

            return File(memoryStream, "text/csv", "filmCalender.csv");
        }

    }
}

PRN231_Web_Razor/Pages/Admin/RoomManagement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Project_Cinema_PRN231.domain.room;
using Project_Cinema_PRN231.model;
using System.Text;


namespace PRN231_Web_Razor.Pages.Admin
{
    public class RoomManagementModel : PageModel
    {
        public IList<Room> RoomList { get; set; }
        [BindProperty]
        public Room Rooms { get; set; }
        public void OnGet()
        {
            HttpClient _httpClient = new HttpClient();
            HttpResponseMessage response = _httpClient.GetAsync("http://localhost:5000/api/Room/getAll").Result;
            var RoomDtos = response.Content.ReadFromJsonAsync<List<RoomDto>>().Result;
            ViewData["RoomDto"] = RoomDtos.ToList();

        }

        public async Task<IActionResult> OnPostEditRoom()
        {
            var idUpdate = int.Parse(Request.Form["id"]);
            var nameUpdate = Request.Form["name"];

            HttpClient client = new HttpClient();
            HttpResponseMessage responseById = client.GetAsync("http://localhost:5000/api/Room/getAll/?$filter=id%20eq%20" + idUpdate).Result;
            var room = responseById.Content.ReadFromJsonAsync<List<Room>>().Result;
            Room c = room[0];
            c.Name = nameUpdate;

            var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5000/api/Room/update");
            request.Headers.Add("Accept", "*/*");
            var jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(c);
            var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
            request.Content = content;
            // Await the asynchronous call to send the request
            var response = await client.SendAsync(request);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAddRoom()
        {
            var createRoomCode = Request.Form["createRoomCode"];
            var createRoomName = Request.Form["createRoomName"];
            Room c = new Room();
            c.Name = createRoomName;
            c.Code = createRoomCode;
            c.BuildingId = 1;
            HttpClient client = new HttpClient();
            var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5000/api/Room/add");
            request.Headers.Add("Accept", "*/*");
            var jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(c);
            var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
            request.Content = content;
            // Await the asynchronous call to send the request
            var response = await client.SendAsync(request);

            return RedirectToPage();
        }
        }
}

PRN231_Web_Razor/Pages/Admin/CategoryManagement.cshtml
@page
@model Library.Pages.Admin.CategoryManagementModel
@using System.Text.Json
@using System.Text.Json.Serialization
@using Project_Cinema_PRN231.model
@{
    Layout = "Shared/_LayoutAdmin";

}
<div id="main">
    <header class="mb-3">
        <a href="#" class="burger-btn d-block d-xl-none">
            <i class="bi bi-justify fs-3"></i>
        </a>
    </header>

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3>Category Management</h3>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="dashboard">Dashboard</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Category Management</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <section class="section">
            <div class="card">
                <div class="card-header">
                    @* <form asp-page="/Admin/CategoryManagement" asp-page-handler="ExportFile" method="POST"> *@
                    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAdd">Add a new category</button>
                    <button onclick="exportData()" class="btn btn-primary">Export file</button><br /><br />

                    <form method="post" asp-page-handler="ImportFile" enctype="multipart/form-data">
                        <input type="file" name="csvFile" />
                        <button type="submit">Import</button>
                    </form>
                </div>

                @*  @if (!string.IsNullOrEmpty(Model.ImportMessage))
                {
                <p>@Model.ImportMessage</p>
                } *@
                <div class="card-body">
                    <table class="table table-striped" id="table1">
                        <thead>
                            <tr>
                                <th>Category ID</th>
                                <th>Category Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model.Categories)
                            {
                                <tr>

                                    <td>@item.Id</td>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        <!--Modal trigger-->
                                        <a data-toggle="modal" data-target="#modalEdit" class='sidebar-link clickingEdit' data-categoryid="@item.Id" data-categoryname="@item.Name" data-imageurl="@item.Image">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                        &nbsp;
                                        <a data-toggle="modal" data-target="#modalView" class='sidebar-link clickingView' data-categoryid="@item.Id" data-categoryname="@item.Name" data-imageurl="@item.Image">

                                            <i class="fa fa-eye"></i>
                                        </a>


                                        <!-- End Modal trigger -->
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>

        </section>
    </div>


</div>


<div class="modal hide fade" id="modalEdit">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <form asp-page="/Admin/CategoryManagement" asp-page-handler="EditCategory" method="POST" enctype="multipart/form-data">
                <input type="hidden" id="categoryid" name="id">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Edit Category</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label for="categoryname" class="col-form-label">Category Name:</label>
                        <input type="text" class="form-control" id="categoryname" name="name">
                    </div>
                    <div class="form-group">
                        <label for="image" class="col-form-label">Image:</label>
                        <img class="form-control" id="image" name="image" style="height: fit-content" />
                        <input type="file" name="newimage" id="newimage">
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal hide fade" id="modalView">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">


            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">User Information</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="form-group">
                    <label for="categoryname" class="col-form-label">Category Name:</label>
                    <input type="text" class="form-control" id="categorynames" name="name" disabled>
                </div>
                <div class="form-group">
                    <label for="image" class="col-form-label">Image:</label>
                    <img class="form-control" id="imageview" name="image" style="height: fit-content" />
                </div>

            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

<div class="modal hide fade" id="modalAdd">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">


            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Add a new category</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form asp-page="/Admin/CategoryManagement" asp-page-handler="AddCategory" method="POST" enctype="multipart/form-data">

                <!-- Modal body -->
                <div class="modal-body">
                    @* <div class="form-group">
                    <label asp-for="Category.CategoryName" class="col-form-label"></label>
                    <input asp-for="Category.CategoryName" class="form-control">

                    </div><div class="form-group">
                    <label asp-for="Image" class="col-form-label"></label>
                    <input asp-for="Image" class="form-control">

                    </div> *@
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" value="Add" class="btn btn-primary" />
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </form>

        </div>
    </div>
</div>

<script>
    // Simple Datatable
    let table1 = document.querySelector('#table1');
    let dataTable = new simpleDatatables.DataTable(table1);
</script>
<script>
    $(document).ready(function () {
        $(".clickingEdit").click(function () { // Click to only happen on announce links
            $("#image").attr("src", $(this).data('imageurl'));
            $("#categoryname").val($(this).data('categoryname'));
            $("#categoryid").val($(this).data('categoryid'));
            $('#modalEdit').modal('show');
        });
    });
</script>



<script>
    $(document).ready(function () {
        $(".clickingView").click(function () { // Click to only happen on announce links
            $("#categorynames").val($(this).data('categoryname'));
            $("#categoryid").val($(this).data('categoryid'));
            $("#imageview").attr("src", $(this).data('imageurl'));

            $('#modalView').modal('show');
        });
    });
</script>

<script>
    function exportData() {
        fetch('/Admin/CategoryManagement?handler=ExportFile')
            .then(response => {
                if (!response.ok) {
                    throw new Error('Export failed');
                }
                return response.blob();
            })
            .then(blob => {
                var url = window.URL.createObjectURL(blob);
                var a = document.createElement('a');
                a.href = url;
                a.download = 'data.csv';
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
            })
            .catch(error => {
                console.error('Export failed:', error);
                alert('Export failed. Please try again later.');
            });
    }
</script>
<script>
    @* $(document).ready(function () {
        $(".deleteBtn").click(function () { // Click to only happen on announce links
        const categoryId = $(this).data('categoryid');

        $.ajax({
        url: '/Admin/CategoryManagement?handler=DeleteCategory',
        type: 'GET',
        data: { categoryId: categoryId },
        success: function (response) {
        if(response == "1"){
        alert("Delete successfully!");
        location.reload();
        }
        else{
        alert("Category is being used!");
        }
        },
        error: function (xhr, status, error) {
        console.error(error);
        }

        });
        });
        }); *@
</script>